---
title: "Deep_vs_Shallow_ED50"
output: html_document
date: "2024-08-14"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r libraries}
#setwd to source file location
library(lmerTest)
library(emmeans)
library(drc)
library(Rmisc)
library(ggplot2)
library(tidyr)
library(dplyr)
library(plyr)
library(reshape2)
library(tidyverse)
library(broom)
library(forcats)
library(openxlsx)
```

# Load Pam Data 
```{r PAM_data}
# Load in PAM Data 
Shall <-read.xlsx("data/PAM/2023-04-05_Mgris_Fagatele_Shallow_PAM.xlsx") %>%
  mutate(Depth = "Shallow") %>%
  rename(Temperature = Temp)

Deep <- read.xlsx("data/PAM/2023-03-30_Mgris_Pspec_Fagatele_Deep_PAM.xlsx") %>%
  filter(Genus == "Montipora")

PAM_data <- rbind(Shall, Deep) %>%
  select(Site, Depth, Genus, Species, Timepoint, Treatment, Temperature, Geno, PAM1, PAM2, PAM3, PAM)

PAM_data$Site<-as.factor(PAM_data$Site)
PAM_data$Depth<-as.factor(PAM_data$Depth)
PAM_data$Genus<-as.factor(PAM_data$Genus)
PAM_data$Geno<-as.factor(PAM_data$Geno)
PAM_data$Species<-as.factor(PAM_data$Species)
PAM_data$Timepoint<-as.factor(PAM_data$Timepoint)

PAM_data<-subset(PAM_data, Timepoint == 'TP')

PAM_data$Site_Genus[Name=(PAM_data$Site == "Fagatele") & (PAM_data$Genus=="Montipora")& (PAM_data$Depth=="Shallow")]<-"Fagatele_Montipora_shallow"

PAM_data$Site_Genus[Name=(PAM_data$Site == "Fagatele") & (PAM_data$Genus=="Montipora")& (PAM_data$Depth=="Deep")]<-"Fagatele_Montipora_deep"

PAM_data$Site_Genus<-as.factor(PAM_data$Site_Genus)

str(PAM_data)

Shallow_data<-subset(PAM_data, Depth == 'Shallow')
Deep_data<-subset(PAM_data, Depth == 'Deep')
```

# Run LL.3() Model and Extract Coefficients
```{r Montipora_shallow}
# drm geno
Montipora_shallow <- drm(PAM ~ Temperature, data = Shallow_data, curveid=Geno, fct = LL.3())

summary(Montipora_shallow)
plot(Montipora_shallow)

# drm pop
Montipora_shallow_pop <- drm(PAM ~ Temperature, data = Shallow_data, fct = LL.3())

summary(Montipora_shallow_pop)
plot(Montipora_shallow_pop)

#extract coeffs by geno, then compute 95% CIs
Montipora_shallow_genocoeffs_50<-data.frame(ED(Montipora_shallow, c(50)))
Montipora_shallow_coeff_mean<-mean(Montipora_shallow_genocoeffs_50$Estimate)
Montipora_shallow_coeff_mean

Montipora_shallow_coeff_sd<-sd(Montipora_shallow_genocoeffs_50$Estimate)
Montipora_shallow_coeff_sd

Montipora_shallow_summary<-data.frame(CI(Montipora_shallow_genocoeffs_50$Estimate, ci=0.95))
Montipora_shallow_coeff_lower<-Montipora_shallow_summary[3,]
Montipora_shallow_coeff_upper<-Montipora_shallow_summary[1,]
```

```{r Montipora_deep}
# drm geno
Montipora_deep <- drm(PAM ~ Temperature, data = Deep_data, curveid=Geno, fct = LL.3())

summary(Montipora_deep)
plot(Montipora_deep)

# drm pop
Montipora_deep_pop <- drm(PAM ~ Temperature, data = Deep_data, fct = LL.3())

summary(Montipora_deep_pop)
plot(Montipora_deep_pop)

#extract coeffs by geno, then compute 95% CIs
Montipora_deep_genocoeffs_50<-data.frame(ED(Montipora_deep, c(50)))
Montipora_deep_coeff_mean<-mean(Montipora_deep_genocoeffs_50$Estimate)
Montipora_deep_coeff_mean

Montipora_deep_coeff_sd<-sd(Montipora_deep_genocoeffs_50$Estimate)
Montipora_deep_coeff_sd

Montipora_deep_summary<-data.frame(CI(Montipora_deep_genocoeffs_50$Estimate, ci=0.95))
Montipora_deep_coeff_lower<-Montipora_deep_summary[3,]
Montipora_deep_coeff_upper<-Montipora_deep_summary[1,]
```

## Combine genotpye-ED50s into dataframe for statistical analysis
```{r ED50s }
Montipora_shallow_ED50s<-data.frame(Montipora_shallow_genocoeffs_50[,1])

Montipora_deep_ED50s<-data.frame(Montipora_deep_genocoeffs_50[,1])

Geno_ED50s<-list(Montipora_shallow_ED50s, Montipora_deep_ED50s) %>% 
  map(~ .x %>% 
        as.data.frame %>%
        rownames_to_column('rn')) %>% 
  reduce(full_join, by = 'rn') %>%
  column_to_rownames('rn')

Geno_ED50s<-Geno_ED50s %>% 
  dplyr::rename(Montipora_shallow=Montipora_shallow_genocoeffs_50...1.,
                Montipora_deep=Montipora_deep_genocoeffs_50...1.,)

Geno_ED50s$Geno<-as.factor(1:nrow(Geno_ED50s))
str(Geno_ED50s)

Geno_ED50s_long<-melt(Geno_ED50s, id="Geno")

Geno_ED50s_long<-Geno_ED50s_long %>% 
  dplyr::rename(Site_Genus= variable,
                ED50=value)

Geno_ED50s_long<-na.omit(Geno_ED50s_long)
```

## Compare groups and create rank_table
```{r rank tables}
#Compare groups statistically
ED50_mod<-aov(ED50 ~ Site_Genus, Geno_ED50s_long)
summary(ED50_mod)
TukeyHSD(ED50_mod)

# Create Rank table
Rank_table<-Geno_ED50s_long %>%
  arrange(Geno, Site_Genus) %>%
  group_by(Site_Genus) %>% 
  mutate(rank_order = rank(desc(ED50))) %>%
  arrange(rank_order)

#write.csv(Rank_table,'Genotype_ranks_full.csv')

Top_performers<-Rank_table %>%
  group_by(Site_Genus) %>%
  slice_min(rank_order, n=5)

Bottom_performers<-Rank_table %>%
  group_by(Site_Genus) %>%
  slice_max(rank_order, n=5)

#write.csv(Top_bottom_performers,'Genotype_ranks_top-bottom-performers.csv')
```

## Combine ED50 data plus predict curves from models for population-level plotting
```{r Coeff_means/lowers/uppers}
Coeff_means<-data.frame(Montipora_shallow_coeff_mean,Montipora_deep_coeff_mean)

Coeff_lowers<-data.frame(Montipora_shallow_coeff_lower,Montipora_deep_coeff_lower)

Coeff_uppers<-data.frame(Montipora_shallow_coeff_upper,Montipora_deep_coeff_upper)
```

```{r preddata}
Montipora_shallow_preddata = data.frame(temp = seq(29,38, length.out = 100))
Montipora_shallow_pred = as.data.frame(predict(Montipora_shallow_pop, newdata = Montipora_shallow_preddata, interval = 'confidence'))
Montipora_shallow_preddata = data.frame(Montipora_shallow_preddata, fvfm = Montipora_shallow_pred$Prediction, Lower = Montipora_shallow_pred$Lower, Upper = Montipora_shallow_pred$Upper)

Montipora_deep_preddata = data.frame(temp = seq(29,38, length.out = 100))
Montipora_deep_pred = as.data.frame(predict(Montipora_deep_pop, newdata = Montipora_deep_preddata, interval = 'confidence'))
Montipora_deep_preddata = data.frame(Montipora_deep_preddata, fvfm = Montipora_deep_pred$Prediction, Lower = Montipora_deep_pred$Lower, Upper = Montipora_deep_pred$Upper)
```

```{r Plot Deep vs Shallow}
ggplot() +
  geom_jitter(data = PAM_data, aes(x = Temperature, y = PAM, color = Depth), size = 1, width = 0.25) +
  scale_x_continuous(limits=c(28.5,38.5), breaks=c(28,30,32,34,36,38)) +
  scale_y_continuous(limits=c(0, 0.7)) +
  ggtitle("Fagatele 2023 M.gris Deep vs Shallow ED50") +
  
  geom_line(data = Montipora_shallow_preddata, aes(x = temp, y = fvfm), color = 'violetred1', show.legend = FALSE, size = 1) +
  geom_ribbon(data = Montipora_shallow_preddata, aes(x = temp, ymin=Lower, ymax=Upper), color = 'violetred1', linetype=2, alpha = 0.2, size = 0.5) +
  geom_vline(data = Coeff_means, aes(xintercept = Montipora_shallow_coeff_mean), color = 'violetred1', show.legend = FALSE, size = 1) +
  annotate("rect", xmin=Coeff_lowers$Montipora_shallow_coeff_lower, xmax=Coeff_uppers$Montipora_shallow_coeff_upper, ymin=-Inf, ymax=Inf, fill= 'violetred1',  alpha = 0.1) +
  geom_text(data = Coeff_means, aes(label=paste0("Shallow Mean ED50 = ", round(Montipora_shallow_coeff_mean, digits = 2), " °C")), x = 30, y = 0.02, show.legend = FALSE, color = 'violetred1', fontface = 'bold') +
  
  geom_line(data = Montipora_deep_preddata, aes(x = temp, y = fvfm), color = 'purple2', show.legend = FALSE, size = 1) +
  geom_ribbon(data = Montipora_deep_preddata, aes(x = temp, ymin=Lower, ymax=Upper), color = 'purple2', linetype=2, alpha = 0.2, size = 0.5) +
  geom_vline(data = Coeff_means, aes(xintercept = Montipora_deep_coeff_mean), color = 'purple2', show.legend = FALSE, size = 1) +
  annotate("rect", xmin=Coeff_lowers$Montipora_deep_coeff_lower, xmax=Coeff_uppers$Montipora_deep_coeff_upper, ymin=-Inf, ymax=Inf, fill= 'purple2',  alpha = 0.1) +
  geom_text(data = Coeff_means, aes(label=paste0("Deep Mean ED50 = ", round(Montipora_deep_coeff_mean, digits = 2), " °C")), x = 29.8, y = 0.0, show.legend = FALSE, color = 'purple2', fontface = 'bold') +
  annotate("text", x = 29.1, y = 0.1, label = expression(italic(p) == 0.001), size = 5) +

  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        legend.position = "none",
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(size = 14)) +
  scale_color_manual(values=c('violetred1','purple2')) +
  ylab(bquote(F[v]/F[m]))+ 
  xlab("Temperature (°C)")

ggsave("Plots/Fagatele 2023_Montipora_Shallow_Deep_Curves.png", height = 150, width = 175, units = "mm")

```