---
title: "ED50vsPhys"
output: html_document
date: "2025-12-04"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)
```

# Load data
```{r}
EDs <- read_xlsx("data/PAM/ED_df_master.xlsx")

sample_data <- read_xlsx("data/frag_data/2023-AS_NMS_Mgris_collections.xlsx")

ITS2 <- read_xlsx("data/ITS2/ITS2_type_relabund.xlsx")

pigment <- read_xlsx("data/frag_data/pigment_per_cm2.xlsx")

SIA <- read_xlsx("data/SIA/sia_means_df_clean.xlsx")

PvsE <- read_xlsx("data/respirometry/PvsI_colony_parameters.xlsx")
```

# Make master dataframe 
```{r}
metadata <- sample_data %>%
  select(Geno = Genotype, depth = Depth_Group, colony_depth = Colony_Depth_m, Sample_ID) %>%
  filter(!grepl("Deep_Extra", Sample_ID)) %>%
  filter(depth != "Midd") %>%
  select(depth_Geno = Sample_ID, colony_depth)

ITS2_abun <- ITS2 %>%
  select(sample_name, 
         C15_C15vd_C15ev_C15ww = `C15-C15vd-C15ev-C15ww`, 
         C3, 
         C3_C115d_C1 = `C3-C115d-C1`, 
         C15_C15vd_C15ev = `C15-C15vd-C15ev`, 
         D4_D1ab_D1_D6_D1ns_D1nt = `D4/D1ab-D1-D6-D1ns-D1nt`) %>%
  mutate(depth_Geno = substring(sample_name, first = 13))

pigment_df <- pigment %>%
  pivot_wider(names_from = Pigment, values_from = ug_cm2_pigment) %>%
  select(depth_Geno = Sample, Chl_a_per_cm2:Perid_per_cm2)

SIA_df <- SIA %>%
  mutate(depth_Geno = substring(Sample_ID, first = 13)) %>%
  select(-Sample_ID, -Depth)

PvsE_df <- PvsE %>%
  select(Pmax, alpha, Ek, depth, geno) %>%
  mutate(depth = case_when(depth == "Middle" ~ "Midd",
                           depth == "Shallow" ~ "Shall",
                           depth == "Deep" ~ "Deep"),
         Geno = substring(geno, first = 4),
         depth_Geno = paste0(depth, "_", Geno)) %>%
  select(depth_Geno, Pmax, alpha, Ek)
  

master_df <- EDs %>%
  left_join(metadata, by = "depth_Geno") %>%
  left_join(ITS2_abun, by = "depth_Geno") %>%
  left_join(pigment_df, by = "depth_Geno") %>%
  left_join(SIA_df, by = "depth_Geno") %>%
  left_join(PvsE_df, by = "depth_Geno")
  
```

# Cross comparing things
```{r}
# Dom Syms 
dom_syms <- master_df %>% 
  select(depth_Geno, depth, ED50, colony_depth, C15_C15vd_C15ev_C15ww,
         D4_D1ab_D1_D6_D1ns_D1nt) %>%
  gather(key = "SymType", value = Abundance, -depth_Geno, -depth,
         -ED50, -colony_depth)

# Sym abundance
ggplot(dom_syms, aes(x = Abundance, y = ED50, color = SymType)) +
  geom_point() +
  theme(legend.position = "bottom") +
  ggtitle("Sym Abundance vs ED50")

# Chlorophyll C
ggplot(master_df, aes(x = Chl_c_per_cm2, y = ED50, color = depth)) +
  geom_point() +
  ggtitle("Chlorophyll C vs ED50")

# SIA 
ggplot(master_df, aes(x = mean_CN_ratio, y = ED50, color = depth)) +
  geom_point() +
    ggtitle("C:N vs ED50")

ggplot(master_df, aes(x = mean_d13C, y = ED50, color = depth)) +
  geom_point() +
    ggtitle("C:N vs ED50")

ggplot(master_df, aes(x = mean_d15N, y = ED50, color = depth)) +
  geom_point() +
    ggtitle("C:N vs ED50")

# Colony Depth
ggplot(master_df, aes(x = colony_depth, y = C15_C15vd_C15ev_C15ww)) +
  geom_point() +
  ggtitle("C dom-sym abundance vs Depth")

ggplot(master_df, aes(x =  C15_C15vd_C15ev_C15ww, y = ED50, color = depth)) +
  geom_point() +
  ggtitle("C dom-sym abundance vs Depth")

ggplot(master_df, aes(x = D4_D1ab_D1_D6_D1ns_D1nt, y = ED50, color = depth)) +
  geom_point() +
  ggtitle("D dom-sym abundance vs ED50")
```

```{r PCA attempt}
pca_df <- master_df %>%
  filter(depth_Geno != "Shall_05") %>% # has no pigment Data
  select(Chl_a_per_cm2, Chl_c_per_cm2, Perid_per_cm2)

pca_res <- prcomp(pca_df, scale. = TRUE, center = TRUE)

summary(pca_res)

loadings <- pca_res$rotation
scores   <- as.data.frame(pca_res$x)

scores <- bind_cols(
  master_df %>% 
    filter(depth_Geno != "Shall_05")%>%
    select(Geno, depth),scores)

ggplot(scores, aes(PC1, PC2, color = depth)) +
  geom_point(size = 4) +
  theme_minimal()

round(pca_res$rotation[,1:3], 3)
```


```{r}

ITS2_condensed <- ITS2_abun %>%
  pivot_longer(cols = c("C15_C15vd_C15ev_C15ww", "C3", 
                        "C3_C115d_C1", "C15_C15vd_C15ev", 
                        "D4_D1ab_D1_D6_D1ns_D1nt"),
               names_to = "ITS2_type",
               values_to = "ITS2_abund") %>%
  filter(ITS2_abund > 0) %>%
  mutate(ITS2_dom = case_when(grepl("^C", ITS2_type) & ITS2_abund > 0.5 ~ "Cladocopium", TRUE ~ "Durusdinium"))

pigment_df_condensed <- pigment_df %>%
  pivot_longer(cols = c("Chl_a_per_cm2", "Chl_c_per_cm2", "Perid_per_cm2"),
               names_to = "Pigment",
               values_to = "Pigment_conct")

master_df_condensed <- master_df %>%
  select(Geno:sample_name, Type:Ek) %>%
  left_join(ITS2_condensed, by = "depth_Geno") %>%
  left_join(pigment_df_condensed, by = "depth_Geno")

ggplot(master_df_condensed, aes(x = ITS2_abund, y = ED50)) +
  geom_point() +
  facet_wrap(~ITS2_type)


ggplot(master_df_condensed, aes(x = Pmax, y = ED50, color = ITS2_dom)) +
  geom_point()

Deep_master <- master_df_condensed %>%
  select(depth:colony_depth, Type, Pmax:Ek, ITS2_dom) %>%
  filter(depth == "Deep",
         Type == "Host") %>%
  dplyr::distinct(depth_Geno, .keep_all = TRUE)


shapiro.test(Deep_master$ED50[Deep_master$ITS2_dom == "Cladocopium"])
shapiro.test(Deep_master$ED50[Deep_master$ITS2_dom == "Durusdinium"])

t.test(ED50 ~ ITS2_dom, data = Deep_master)
t.test(alpha ~ ITS2_dom, data = Deep_master)

```

# I don't know trying to see what works 
```{r}
host_df <- master_df %>% filter(Type == "Host")

lm(data = host_df, ED50 ~ Chl_a_per_cm2 + Chl_c_per_cm2 + Perid_per_cm2)

its2_pca <- prcomp(
  host_df[, c("C15_C15vd_C15ev_C15ww",
              "C3",
              "C3_C115d_C1",
              "C15_C15vd_C15ev",
              "D4_D1ab_D1_D6_D1ns_D1nt")],
  scale. = TRUE
)

host_df$ITS2_PC1 <- its2_pca$x[,1]
host_df$ITS2_PC2 <- its2_pca$x[,2]

lm(Pmax ~ ITS2_PC1 + ITS2_PC2, data = host_df)
summary(lm(Pmax ~ ITS2_PC1 + ITS2_PC2, data = host_df))
its2_pca$rotation

summary(lm(Pmax ~ ITS2_PC1 + ITS2_PC2 + depth, data = host_df))

ggplot(host_df, aes(ITS2_PC1, Pmax)) +
  geom_point()
```

