---
title: "Fig_2"
output: html_document
date: "2026-03-04"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Load Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggpubr)
``` 
# Import Figures
```{r}
RLCs <- readRDS(file = "Plots/rlcs/PGH_model_fits.rds") + 
  theme(strip.text = element_text(size = 11),
        plot.margin = margin(5, 7, 0, 0),
        axis.title.x = element_text(color = "transparent", size = 1),
        axis.title = element_text(size = 10),
        panel.spacing.x=unit(0.5, "lines"))

PvsE <- readRDS(file = "Plots/PvsI/pop_gross_PS.rds") +
  theme(plot.margin = margin(0, 7, 0, 0),
        strip.text = element_blank(),
        axis.title = element_text(size = 10),
        panel.spacing.x=unit(0.5, "lines"))


ITS2 <- readRDS(file = "Plots/ITS2/rel_abund_ITS2.rds") +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 6),
        plot.margin = margin(5, 5, 0, 5),
        strip.text = element_text(size = 11),
        panel.spacing.x=unit(0, "lines"))

Pigment <- readRDS(file = "Plots/Pigment/total_pigment.rds") +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 7),
        plot.margin = margin(5, 5, 0, 5),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 9),
        panel.spacing.x=unit(0.5, "lines")) +
  expand_limits(y = 0)
```

# Compile into Fig 2
```{r}
top_row <- ggarrange(
  RLCs, PvsE, 
  ncol = 1,
  align = "hv",
  labels = c("A", "B"))

ggsave(
  filename = "Plots/Fig_2/top_row.png",  # Name of the output file
  plot = top_row,                      # Specify the plot to save
  width = 7.5,                            # Width in inches
  height = 5                            # Height in inches
)

bottom_row <- ggarrange (
  ITS2, Pigment,
  ncol = 2,
  align = "h",
  widths = c(1,1),
  common.legend = FALSE,
  labels = c("C", "D")) 

ggsave(
  filename = "Plots/Fig_2/bottom_row.png",  # Name of the output file
  plot = bottom_row,                      # Specify the plot to save
  width = 7.5,                            # Width in inches
  height = 3                            # Height in inches
)


ggarrange(top_row, bottom_row, ncol = 1,
          heights = c(2,1))


```

