---
title: "Temperature"
output: html_document
date: "2026-01-16"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(tidyverse)
library(hms)
library(FSA)
library(car)
library(rcompanion)
```

# Load Fagatele Buoy Data
```{r}
Fagatele<-read.csv("data/environmental/temperature/FagateleSpot_2022-12-11_2024-05-04.csv", 
                   header=TRUE, sep=",")

Fagatele$sensor_position<-as.factor(Fagatele$sensor_position)

Fagatele$utc_timestamp <- as.POSIXct(Fagatele$utc_timestamp,
  format = "%Y-%m-%dT%H:%M:%OSZ", tz = "Pacific/Pago_Pago")
```

# Clean Up Fagatele Buoy Data
```{r}
end_date <- as.POSIXct("2023-06-01 00:00:00", tz = "Pacific/Pago_Pago")

Fagatele_clean<- Fagatele %>%
  mutate(sensor_position = case_when(sensor_position == "1" ~ "Shallow",
                                     sensor_position == "2" ~ "Mid",
                                     sensor_position == "3" ~ "Deep")) %>%
  filter(utc_timestamp < end_date) %>%
  mutate(Date = as.Date(utc_timestamp, tz = "Pacific/Pago_Pago"),
         Time = as_hms(utc_timestamp), tz = "Pacific/Pago_Pago") %>%
  select(utc_timestamp, Date, Time, Depth = sensor_position, Temperature = value) %>%
  filter(Temperature > 0)
```

# Calculate Fagatele Buoy Hourly Average 
```{r}
head(Fagatele_clean)

Fagatele_hourly <- Fagatele_clean %>%
  mutate(Date = floor_date(utc_timestamp, unit = "hour")) %>%
  group_by(Date, Depth) %>%
  summarise(Temperature = mean(Temperature, na.rm = TRUE), .groups = "keep") %>%
  mutate(Month = month(Date, label = TRUE, abbr = FALSE))
```

# Plot Fagatele Buoy Hourly Average 
```{r}
# Start and End dates for coral collection 
start_collection <- as.POSIXct("2023-03-30 00:00:00", tz = "Pacific/Pago_Pago")
end_collection <- as.POSIXct("2023-04-05 00:00:00", tz = "Pacific/Pago_Pago")

p_temp_series <- ggplot(Fagatele_hourly, aes(x = Date, group = Depth, color = Depth)) +
  geom_line(aes(y = Temperature), linewidth = 0.65, alpha = 0.9) +
  aes(group = rev(Depth)) +
  scale_y_continuous(name = "Hourly Average Temperature (°C)") +
  scale_color_manual(values = c('darkblue', 'dodgerblue3', '#6BAED6')) +
  scale_x_datetime(limits = c(as.POSIXct("2022-12-01"), as.POSIXct("2023-06-10")),
  date_labels = "%b %Y",
  date_breaks = "1 month",
  expand = c(0, 0)) +
  annotate("rect", xmin = start_collection, xmax = end_collection, ymin = -Inf, 
           ymax = Inf,  fill = "#999599", alpha = 0.3) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom") 

saveRDS(p_temp_series, "Plots/Fig_1/p_temp_series.rds")
```

# Calculate and Plot Fagatele Buoy Data Daily Range
```{r stats}
# Calculate daily range
daily_range <- Fagatele_clean %>%
  group_by(Date, Depth) %>%   # group by day and depth
  summarise(daily_max = max(Temperature, na.rm = TRUE),
            daily_min = min(Temperature, na.rm = TRUE),
            daily_range = daily_max - daily_min,
            .groups = "drop")%>%
  mutate(Month = month(Date, label = TRUE, abbr = TRUE)) %>%
  mutate(Year = year(Date)) %>%
  mutate(MonthYear = paste0(Month, " ", Year)) %>%
  mutate(MonthYear = factor(MonthYear, 
                            levels = unique(MonthYear[order(Date)]))) %>%
  mutate(Month_Depth = paste0(Month, "_", Depth))

# Shapiro-Wilk Test 
shapiro.test(daily_range$daily_range)

# Run Kruskal Test 
kruskal.test(data = daily_range, daily_max ~ Month_Depth)

# Run DunnTest 
dunn_res <- dunnTest(daily_range ~ Month_Depth, data = daily_range, method = "holm")

# Generate compact letter display
cld_letters <- cldList(P.adj ~ Comparison, data = dunn_res$res, threshold = 0.05) %>%
    mutate(Depth = str_sub(Group, start = 5),
           Month = str_sub(Group, start = 1, end = 3), 
           Year = case_when(Month == "Dec" ~ 2022, TRUE ~ 2023),
           MonthYear = paste0(Month, " ", Year))

# Plot Daily Range with Compact Letter Display 
p_temp_range <- ggplot(daily_range,aes(x = MonthYear, y = daily_range, fill = Depth)) + 
  geom_boxplot(position = position_dodge(width = 1.1), width = 0.5, 
               outlier.shape = NA) +
  geom_text(data = cld_letters, aes(x = MonthYear, y = -0.04, label = Letter, 
                                    group = Depth),
            position = position_dodge(width = 1.1), inherit.aes = FALSE, size = 2.5,
            vjust = 0, angle = 45) +
  scale_fill_manual(values = c("darkblue", "dodgerblue3", "#6BAED6")) +
  scale_y_continuous(name = "Daily Temperature Range (°C)") +
  theme_bw() +
  theme(axis.title.x = element_blank(), 
        legend.position = "bottom", 
        legend.title = element_blank())

saveRDS(p_temp_range, "Plots/Fig_1/p_temp_range.rds")
```

# 2024 Hobo Data - Supplemental 
```{r}
hobo_10 <- read.delim("./data/environmental/temperature/2023-2024_Hobo_Fagatele_Shallow_10_Bouy_clean.txt") %>%
  mutate(Depth = "Shallow") %>%
  select(DateTime, Temperature = Fagatele_Shallow_10_Bouy, Depth)
 
hobo_20 <- read.delim("./data/environmental/temperature/2023-2024_Hobo_Fagatele_20_clean.txt") %>%
  mutate(Depth = "Midd") %>%
  select(DateTime, Temperature = Fagatele_20, Depth)

hobo_40 <- read.delim("./data/environmental/temperature/2023-2024_Hobo_Fagatele_40_clean.txt") %>%
  mutate(Depth = "Deep") %>%
  select(DateTime, Temperature = Fagatele_40, Depth)

hobo_data <- rbind(hobo_10, hobo_20, hobo_40)
```

# Clean up HoboData for Plotting
```{r}
hobo_data_clean <- hobo_data %>%
  mutate(DateTime = as.POSIXct(hobo_data$DateTime, 
                                 format = "%m/%d/%y %I:%M:%S %p",
                                 tz = "Pacific/Pago_Pago"),
         Month = month(DateTime, label = TRUE, abbr = FALSE),
         Date = as.Date(DateTime, tz = "Pacific/Pago_Pago"),
         Time = as_hms(DateTime), tz = "Pacific/Pago_Pago") %>%
  select(DateTime, Date, Time, Month, Temperature, Depth)
```

# Hourly Hobo Data 
```{r}
hobo_data_hourly <- hobo_data_clean %>%
mutate(Date = floor_date(DateTime, unit = "hour")) %>%
  group_by(DateTime, Depth) %>%
  summarise(Temperature = mean(Temperature, na.rm = TRUE), .groups = "keep") 

hobo_data_hourly <- hobo_data_clean %>%
  mutate(hour = floor_date(DateTime, unit = "hour")) %>%  
  group_by(hour, Depth) %>%                                
  summarise(hourly_temp = mean(Temperature, na.rm = TRUE), .groups = "drop")

```

# Plot Hobo Data
```{r}
ggplot(hobo_data_hourly, aes(x = hour, y = hourly_temp, color = Depth)) +
  geom_line() +
  theme_bw() +
  scale_color_manual(values = c('darkblue', 'dodgerblue3', 'lightblue'))
```

